### ISSUE TITLE
Add Code Example from the Http and Https modules

### ISSUE THREAD

**Issue by atapas** [atapas/nodeX#1]

**Comment by Akshaya101** [comment]
Can I be assigned to this issue?

**Comment by atapas** [comment]
Sure @Akshaya101 Assigned to you.

**Comment by atapas** [comment]
Hey @Akshaya101 

Here are some expectations:

- Please cover as many use cases possible of HTTP and HTTPS modules. Like adding headers, query strings, requests, responses.
- For each of these modules, you need to create a folder at the level of the existing `fs-module` folder to separate them out. Do not code inside the fs-module.
- Please structure the code and create a README as created for the fs-module: https://github.com/atapas/nodeX/tree/main/fs-module

Please ask if you have questions.

**Comment by atapas** [comment]
Closed the issue
