### ISSUE TITLE
Add User Interface to Show the Code examples

### ISSUE THREAD

**Issue by atapas** [atapas/nodeX#2]

**Comment by iShelar** [comment]
What exactly we want to do in this issue? @atapas

**Comment by Tiya0310** [comment]
do we have to provide UI for each code example?

**Comment by atapas** [comment]
The primary vision is to build a website listing the examples we see in this repository.

**Comment by yurireeis** [comment]
hey @atapas ! I've created a simple get started example for this issue (the PR is opened). please let me know if it matches your expectations.

**Comment by yurireeis** [comment]
hi @atapas ! please don't forget to assign this issue to me 👍🏿
