### ISSUE TITLE
All the Parent links gives 404

### ISSUE THREAD

**Issue by atapas** [atapas/nodeX#7]
**Describe the bug**

The Parent link gives 404. It should take the control to the main Readme page.

![image](https://user-images.githubusercontent.com/3633137/194385517-9167cbb2-5fc0-4105-b98f-7059447f1952.png)

**Comment by micaelalex** [comment]
Could you assign me this if possible?

**Comment by micaelalex** [comment]
@atapas Think I fixed it with the pull.
